// <auto-generated />
using System;
using Coop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coop.Migrations
{
    [DbContext(typeof(CoopDbContext))]
    [Migration("20210801045531_Addproduce")]
    partial class Addproduce
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coop.Models.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Coop.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProduceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProduceId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Coop.Models.Produce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProduceNameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProduceNameId");

                    b.ToTable("Produce");
                });

            modelBuilder.Entity("Coop.Models.ProduceFeature", b =>
                {
                    b.Property<int>("ProduceId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("ProduceId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.ToTable("ProduceFeatures");
                });

            modelBuilder.Entity("Coop.Models.ProduceName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProduceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProduceTypeId");

                    b.ToTable("ProduceName");
                });

            modelBuilder.Entity("Coop.Models.ProduceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ProduceTypes");
                });

            modelBuilder.Entity("Coop.Models.Photo", b =>
                {
                    b.HasOne("Coop.Models.Produce", null)
                        .WithMany("Photos")
                        .HasForeignKey("ProduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Coop.Models.Produce", b =>
                {
                    b.HasOne("Coop.Models.ProduceName", "ProduceName")
                        .WithMany()
                        .HasForeignKey("ProduceNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduceName");
                });

            modelBuilder.Entity("Coop.Models.ProduceFeature", b =>
                {
                    b.HasOne("Coop.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coop.Models.Produce", "Produce")
                        .WithMany("Features")
                        .HasForeignKey("ProduceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Produce");
                });

            modelBuilder.Entity("Coop.Models.ProduceName", b =>
                {
                    b.HasOne("Coop.Models.ProduceType", "ProduceType")
                        .WithMany("ProduceNames")
                        .HasForeignKey("ProduceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduceType");
                });

            modelBuilder.Entity("Coop.Models.Produce", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Coop.Models.ProduceType", b =>
                {
                    b.Navigation("ProduceNames");
                });
#pragma warning restore 612, 618
        }
    }
}
