// <auto-generated />
using Coop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Coop.Migrations
{
    [DbContext(typeof(CoopDbContext))]
    [Migration("20210705123555_InitModel")]
    partial class InitModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Coop.Models.ProduceName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProduceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProduceTypeId");

                    b.ToTable("ProduceName");
                });

            modelBuilder.Entity("Coop.Models.ProduceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("produceTypes");
                });

            modelBuilder.Entity("Coop.Models.ProduceName", b =>
                {
                    b.HasOne("Coop.Models.ProduceType", "ProduceType")
                        .WithMany("ProduceNames")
                        .HasForeignKey("ProduceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProduceType");
                });

            modelBuilder.Entity("Coop.Models.ProduceType", b =>
                {
                    b.Navigation("ProduceNames");
                });
#pragma warning restore 612, 618
        }
    }
}
